# Generated by Django 4.1.1 on 2022-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementpage',
            name='Cible',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
