# Generated by Django 4.1.1 on 2022-11-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('page_projets', '0002_elementpage_cible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementPage',
            new_name='Single_projectPage',
        ),
    ]
