# Generated by Django 4.1.1 on 2022-11-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('page_projets', '0003_rename_elementpage_single_projectpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjetsPage',
            new_name='ProjectsPage',
        ),
        migrations.AlterModelOptions(
            name='single_projectpage',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
