# Generated by Django 4.1.1 on 2022-11-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ministere', '0003_remove_administrationpage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_biographypage',
            old_name='noms',
            new_name='fonction',
        ),
    ]
