# Generated by Django 4.1.1 on 2022-11-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0002_rename_postpage_single_postpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='ArticlePage',
        ),
    ]
