# Generated by Django 4.1.1 on 2022-11-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0003_rename_blogpage_articlepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePage',
            new_name='PostPage',
        ),
    ]
