# Generated by Django 4.1.1 on 2022-11-25 01:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_single_postpage_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_postpage',
            name='bod',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.RichTextBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
