# Generated by Django 4.1.1 on 2022-11-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_single_postpage_bod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_postpage',
            old_name='header_image',
            new_name='image',
        ),
    ]
