# Generated by Django 4.1.1 on 2022-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_patrimoine', '0002_detailpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='titre_ancre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
