# Generated by Django 4.1.1 on 2022-11-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_patrimoine', '0004_rename_patrimoinepage_national_heritagepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='titre_ancre',
        ),
    ]
