# Generated by Django 4.1.1 on 2022-12-01 09:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_patrimoine', '0005_remove_detailpage_titre_ancre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='Table',
            field=wagtail.fields.StreamField([('table_de_matiere', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('slug', wagtail.blocks.TextBlock(editable=True, populate_from='title'))], icon='edit'))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
