# Generated by Django 4.1.1 on 2022-12-01 10:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_patrimoine', '0006_detailpage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='Table',
            field=wagtail.fields.StreamField([('Acces_rapide', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('slug', wagtail.blocks.TextBlock(editable=True, populate_from='title'))], icon='edit'))], use_json_field=True),
        ),
    ]
