# Generated by Django 4.1.1 on 2022-12-01 11:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_patrimoine', '0008_alter_detailpage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='Table',
            field=wagtail.fields.StreamField([('Acces_rapide', wagtail.blocks.StructBlock([('Titre_de_l_ancre', wagtail.blocks.CharBlock(help_text='Saisir le texte du Titre. Ex : Mettre à jour les photos ', max_length=40, required=True)), ('Lien_d_ancre', wagtail.blocks.TextBlock(help_text="Saisir l'ancre de lien. Ex : #mettre-a-jour-les-photos"))], icon='edit'))], use_json_field=True),
        ),
    ]
