# Generated by Django 4.1.1 on 2022-11-23 13:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='secrétariat',
        ),
        migrations.AddField(
            model_name='homepage',
            name='Secretariat',
            field=wagtail.fields.StreamField([('secretariat', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='edit'))], default='', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='administration',
            field=wagtail.fields.StreamField([('administration', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='user'))], use_json_field=True),
        ),
    ]
