# Generated by Django 4.1.1 on 2022-11-23 14:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_secretariat_alter_homepage_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='administration',
            new_name='administration_du_ministere',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Secretariat',
        ),
        migrations.AddField(
            model_name='homepage',
            name='Secretariat_general',
            field=wagtail.fields.StreamField([('secretariat', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=500, required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))], icon='edit'))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
