# Generated by Django 4.1.1 on 2022-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0002_rename_politiquepage_public_policiespage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpagedocument',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='public_policiespage',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
