# Generated by Django 4.1.1 on 2022-11-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0003_alter_fichierpagedocument_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpagedocument',
            name='document',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
