# Generated by Django 4.1.1 on 2022-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0004_alter_fichierpagedocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierpagedocument',
            name='title',
            field=models.CharField(blank=True, help_text='Ajouter le titre du document', max_length=255),
        ),
    ]
