# Generated by Django 4.1.1 on 2022-11-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0005_fichierpagedocument_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierpagedocument',
            name='title',
        ),
    ]
