# Generated by Django 4.1.1 on 2022-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0006_remove_fichierpagedocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierpagedocument',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
