# Generated by Django 4.1.1 on 2023-01-05 16:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0007_alter_fichierpagedocument_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichierpagedocument',
            options={'verbose_name': 'Politique Publique', 'verbose_name_plural': 'Politique Publique'},
        ),
        migrations.AddField(
            model_name='public_policiespage',
            name='description_page',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='fichierpagedocument',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='page_politiques_publiques.public_policiespage'),
        ),
        migrations.DeleteModel(
            name='Single_public_policyPage',
        ),
    ]
