# Generated by Django 4.1.1 on 2023-01-05 16:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0008_alter_fichierpagedocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichierpagedocument',
            options={'ordering': ['sort_order']},
        ),
        migrations.CreateModel(
            name='BlogPageRelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, upload_to='')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='page_politiques_publiques.public_policiespage')),
            ],
            options={
                'verbose_name': 'Politique Publique',
                'verbose_name_plural': 'Politique Publique',
            },
        ),
    ]
