# Generated by Django 4.1.1 on 2023-01-10 10:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0011_blogpagerelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagerelatedlink',
            name='url',
        ),
        migrations.AddField(
            model_name='blogpagerelatedlink',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpagerelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='page_politiques_publiques.single_public_policypage'),
        ),
        migrations.DeleteModel(
            name='FichierPageDocument',
        ),
    ]
