# Generated by Django 4.1.1 on 2023-01-10 12:28

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0012_remove_blogpagerelatedlink_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_policiespage',
            name='document',
            field=wagtail.fields.StreamField([('administration', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('Document', wagtail.documents.blocks.DocumentChooserBlock(required=False))], icon='user'))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
