# Generated by Django 4.1.1 on 2023-01-10 12:41

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0013_public_policiespage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_policiespage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StreamBlock([('image', wagtail.blocks.TextBlock()), ('quotation', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock())])), ('video', wagtail.blocks.TextBlock())], icon='cogs'))], default='', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='public_policiespage',
            name='document',
            field=wagtail.fields.StreamField([('administration', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('Document', wagtail.documents.blocks.DocumentChooserBlock(max_num=3, min_num=1, required=False))], icon='user'))], use_json_field=True),
        ),
    ]
