# Generated by Django 4.1.1 on 2023-01-10 12:44

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0014_public_policiespage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_policiespage',
            name='body',
        ),
        migrations.AlterField(
            model_name='public_policiespage',
            name='document',
            field=wagtail.fields.StreamField([('administration', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('quotation', wagtail.blocks.StructBlock([('Document', wagtail.documents.blocks.DocumentChooserBlock(max_num=3, min_num=1, required=False))]))], icon='user'))], use_json_field=True),
        ),
    ]
