# Generated by Django 4.1.1 on 2023-01-10 13:28

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_politiques_publiques', '0016_public_policiespage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_public_policypage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='single_public_policypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='single_public_policypage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='single_public_policypage',
            name='struct_org_logo',
        ),
        migrations.AlterModelOptions(
            name='public_policiespage',
            options={'verbose_name': 'Politique Publique', 'verbose_name_plural': 'Politique Publique'},
        ),
        migrations.RemoveField(
            model_name='public_policiespage',
            name='body',
        ),
        migrations.AlterField(
            model_name='public_policiespage',
            name='document',
            field=wagtail.fields.StreamField([('Article', wagtail.blocks.StructBlock([('Description', wagtail.blocks.CharBlock(help_text='Ajouter la description ', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(max_length=255, required=True)), ('Document', wagtail.blocks.StreamBlock([('Ajouter', wagtail.documents.blocks.DocumentChooserBlock(required=False))], max_num=2, min_num=1))], icon='cogs'))], use_json_field=True),
        ),
        migrations.DeleteModel(
            name='BlogPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='Single_public_policyPage',
        ),
    ]
